Social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    path('reset', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>/',
         views.UserUnfollowView.as_view(), name='unfollow'),
    path('followers/<int:user_id>/',
         views.ShowFollowersView.as_view(), name='followers'),
    path('following/<int:user_id>/',
         views.ShowFollowingView.as_view(), name='followings'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('post/<int:post_id>/<slug:post_slug>',
         views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/',
         views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/',
         views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/',
         views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'phone_number', 'full_name']

    def __str__(self):
        return self.username

    @property
    def is_staff(self):
        return self.is_admin


class Relation(models.Model):
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='followings')
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='followers')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} is following {self.to_user}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)

accounts/forms.py
from django import forms
from .models import User, Profile
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Comfirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'phone_number', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords didnt match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text="you can change using <a href=\"../password/\">this form</a>")

    class Meta:
        model = User
        fields = ('username', 'email', 'phone_number', 'full_name',
                  'password', 'last_login')


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone_number = forms.CharField(max_length=11)
    full_name = forms.CharField(label='Full name')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Comfirm Password', widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('This email already exists')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('this username already exits')
        return username

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords didnt match')
        return cd['password2']


class UserLoginForm(forms.Form):
    username = forms.CharField(label='username or Phone number',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class EditUserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Profile
        fields = ('age', 'bio')

accounts/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegistrationForm, UserLoginForm, EditUserForm
from .models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Relation


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['phone_number'],
                                     cd['full_name'], cd['password1'])
            messages.success(request, 'you registered successfully', 'success')
            return redirect('home:home')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(
                    request, 'you logged in successfully', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request, 'username or password is wrong', 'danger')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    def setup(self, request, *args, **kwargs):
        self.user_instance = get_object_or_404(User, pk=kwargs['user_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, user_id):
        is_following = False
        user = get_object_or_404(User, pk=user_id)
        posts = user.posts.all()
        followers = self.user_instance.followers.all()
        followings = self.user_instance.followings.all()
        relation = Relation.objects.filter(
            from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(request, 'accounts/profile.html', {'user': user, 'posts': posts, 'is_following': is_following,
                                                         'followers': followers, 'followings': followings})


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserFollowView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['user_id'])
        relation = Relation.objects.filter(
            from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(
                request, 'You are already following this account', 'danger')
        else:
            Relation(from_user=request.user, to_user=user).save()
            messages.success(
                request, 'you followed this account', 'success')
        return redirect('accounts:profile', user.id)


class UserUnfollowView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['user_id'])
        relation = Relation.objects.filter(
            from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()

            messages.success(request, 'You unfollowed this account', 'success')
        else:
            messages.error(
                request, 'you are not following this user', 'danger')
        return redirect('accounts:profile', user.id)


class ShowFollowersView(LoginRequiredMixin, View):
    def setup(self, request, *args, **kwargs):
        self.user_instance = get_object_or_404(User, pk=kwargs['user_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['user_id'])
        followers = self.user_instance.followers.all()
        return render(request, 'accounts/followers.html', {'user': user, 'followers': followers})


class ShowFollowingView(LoginRequiredMixin, View):
    def setup(self, request, *args, **kwargs):
        self.user_instance = get_object_or_404(User, pk=kwargs['user_id'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs['user_id'])
        followings = self.user_instance.followings.all()
        return render(request, 'accounts/followings.html', {'user': user, 'followings': followings})


class EditUserView(LoginRequiredMixin, View):
    form_class = EditUserForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile, initial={
                               'email': request.user.email})
        return render(request, 'accounts/edit_profile.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(
                request, 'your profile edited successfully', 'success')
            return redirect('accounts:profile', request.user.id)

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
</form>
{% endblock %}

accounts/templates/accounts/followers.html
{% extends 'base.html' %}

{% block content %}
<p>{{ user.username }}</p>
<hr>
<h3>Followers</h3>
{% for follower in followers %}
<a href="{% url 'accounts:profile' follower.from_user.id %}">{{ follower.from_user }}</a>
{% empty %}
<p> this user has no follower </p>
{% endfor %}
{% endblock %}

accounts/templates/accounts/followings.html
{% extends 'base.html' %}

{% block content %}
<p>{{ user.username }}</p>
<hr>
<h3>Following</h3>
{% for following in followings %}
<a href="{% url 'accounts:profile' following.to_user.id %}">{{ following.to_user }}</a>
{% empty %}
<p>this account has no following yet</p>
{% endfor %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Login</h2>
<form action="" method="post" novalidate class="col-md-6">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<p>Your password changed successfully</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
{% if validlink %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change">
</form>
{% else %}
<p>This link is not valid please try again</p>
{% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<p>check your email</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
if you want to change your email click on this link:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">{{ user.username }}</h2>
{% if request.user.id != user.id and not is_following %}
<a href="{% url 'accounts:follow' user.id %}" class="btn btn-outline-dark">Follow</a>
{% elif request.user.id != user.id and is_following %}
<a href="{% url 'accounts:unfollow' user.id %}" class="btn btn-dark">Unfollow</a>
{% endif %}

<a href="{% url 'accounts:followers' user.id %}" class="btn btn-dark">Followers {{ followers.count }}</a>
<a href="{% url 'accounts:followings' user.id %}" class="btn btn-dark">Followings {{ followings.count }}</a>

<div class="car">
    {% for post in posts %}
    <a class="card-body" href="{{ post.get_absolute_url }}">
        <div class="post">{{ post.body|truncatewords:8 }}</div>
    </a>
    {% endfor %}
    {% if request.user.id == user.id %}
    <a href="{% url 'home:post_create' %}" class="btn btn-primary">Create</a>
    <a href="{% url 'accounts:edit_user' %}" class="btn btn-info">Edit Profile</a>
    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register user</h2>
<form action="" method="post" class="col-md-6" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
{% endblock %}